export const types = {
  GET_PERSONAGE_START: 'GET_PERSONAGE_START',
  GET_PERSONAGE_SUCCESS: 'GET_PERSONAGE_SUCCESS',
  GET_PERSONAGE_FAIL: 'GET_PERSONAGE_FAIL',

  ADD_PERSONAGE_FAVORITE: 'ADD_PERSONAGE_FAVORITE',

  REMOVE_PERSONAGE_FAVORITE: 'REMOVE_PERSONAGE_FAVORITE',

  GET_PERSONAGE_NEXT_PAGE_START: 'GET_PERSONAGE_NEXT_PAGE_START',
  GET_PERSONAGE_NEXT_PAGE_SUCCESS: 'GET_PERSONAGE_NEXT_PAGE_SUCCESS',
  GET_PERSONAGE_NEXT_PAGE_FAIL: 'GET_PERSONAGE_NEXT_PAGE_FAIL',
};
